# Generated by Django 5.2.7 on 2025-10-23 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0007_remove_assignment_topics"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
