repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1 # ruff-pre-commit latest version
    hooks:
      - id: ruff
        args: [--fix, --line-length=120] # auto fix + max line length 120
        files: ^(backend/|research/)
      - id: ruff-format
        args: [--line-length=120]
        files: ^(backend/|research/)

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=120"]
        files: ^(backend/|research/)

  - repo: https://github.com/psf/black
    rev: 25.9.0 # black latest version
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=120]
        files: ^(backend/|research/)
