[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "backend.voicetutor.settings"  # 실제 경로
python_files = ["test_*.py"]
pythonpath = ["backend"]  # 추가
