# Generated by Django 5.2.7 on 2025-10-23 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[("correct", "Correct"), ("incorrect", "Incorrect")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("text_answer", models.TextField(blank=True)),
                ("eval_grade", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="questions.question"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["student"], name="submissions_student_f22db1_idx"),
                    models.Index(fields=["question"], name="submissions_questio_b431e4_idx"),
                ],
                "unique_together": {("question", "student")},
            },
        ),
        migrations.CreateModel(
            name="PersonalAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                            ("GRADED", "Graded"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("solved_num", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_assignments",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "personal_assignment",
                "indexes": [
                    models.Index(fields=["student"], name="personal_as_student_77fe52_idx"),
                    models.Index(fields=["assignment"], name="personal_as_assignm_a2489f_idx"),
                    models.Index(fields=["status"], name="personal_as_status_094827_idx"),
                ],
                "unique_together": {("student", "assignment")},
            },
        ),
    ]
