# Generated by Django 5.2.7 on 2025-10-11 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                            ("GRADED", "Graded"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("solved_num", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_assignments",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "personal_assignment",
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField(help_text="문항 번호 (1..N)")),
                ("content", models.CharField(blank=True, max_length=255)),
                ("hint", models.CharField(blank=True, max_length=255, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("model_answer", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "personal_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="submissions.personalassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["personal_assignment_id", "number"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[("correct", "Correct"), ("incorrect", "Incorrect")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("text_answer", models.TextField(blank=True)),
                ("eval_grade", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="submissions.questions"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="personalassignment",
            index=models.Index(fields=["student"], name="personal_as_student_77fe52_idx"),
        ),
        migrations.AddIndex(
            model_name="personalassignment",
            index=models.Index(fields=["assignment"], name="personal_as_assignm_a2489f_idx"),
        ),
        migrations.AddIndex(
            model_name="personalassignment",
            index=models.Index(fields=["status"], name="personal_as_status_094827_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="personalassignment",
            unique_together={("student", "assignment")},
        ),
        migrations.AddIndex(
            model_name="questions",
            index=models.Index(fields=["personal_assignment", "number"], name="submissions_persona_998a57_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="questions",
            unique_together={("personal_assignment", "number")},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["student"], name="submissions_student_f22db1_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["question"], name="submissions_questio_b431e4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("question", "student")},
        ),
    ]
