# Generated by Django 5.2.7 on 2025-11-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalassignment",
            name="status",
            field=models.CharField(
                choices=[("NOT_STARTED", "Not Started"), ("IN_PROGRESS", "In Progress"), ("SUBMITTED", "Submitted")],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
