# Generated by Django 5.2.7 on 2025-11-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_alter_personalassignment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("correct", "Correct"), ("incorrect", "Incorrect"), ("PROCESSING", "Processing")],
                max_length=32,
                null=True,
            ),
        ),
    ]
