name: "UI/UX Improvement"
description: "화면 구성이나 인터랙션 관련 개선 사항을 제안할 때 사용하세요."
title: "[UI/UX]: "
labels: ["ui-ux", "design"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## 화면/UI 개선 제안"
  - type: textarea
    id: current
    attributes:
      label: "현재 화면/동작"
      description: "현재 UI나 UX의 문제점을 설명해주세요."
      placeholder: "예: 버튼 색상이 배경과 너무 유사해서 잘 보이지 않습니다."

  - type: textarea
    id: suggestion
    attributes:
      label: "개선 제안"
      description: "어떻게 개선되면 좋을지 구체적으로 적어주세요."
      placeholder: "예: 버튼 색상을 primary color로 변경하면 좋겠습니다."

  - type: input
    id: screen
    attributes:
      label: "관련 화면 이름 (선택)"
      placeholder: "예: LoginScreen, AssignmentScreen 등"
