# Generated by Django 5.2.7 on 2025-10-11 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="course_classes", to="catalog.subject"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("ENROLLED", "Enrolled"), ("DROPPED", "Dropped"), ("COMPLETED", "Completed")],
                        default="ENROLLED",
                        max_length=20,
                    ),
                ),
                (
                    "course_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.courseclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="courseclass",
            index=models.Index(fields=["teacher"], name="courses_cou_teacher_4430fc_idx"),
        ),
        migrations.AddIndex(
            model_name="courseclass",
            index=models.Index(fields=["subject"], name="courses_cou_subject_ab4934_idx"),
        ),
        migrations.AddIndex(
            model_name="courseclass",
            index=models.Index(fields=["start_date", "end_date"], name="courses_cou_start_d_7bb67f_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["student"], name="courses_enr_student_5c0023_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["course_class"], name="courses_enr_course__42cd3d_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="courses_enr_status_4fd017_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course_class")},
        ),
    ]
