# Generated by Django 5.2.7 on 2025-10-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseclass',
            old_name='title',
            new_name='name',
        ),
    ]
