# Generated by Django 5.2.7 on 2025-11-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courseclass',
            name='courses_cou_start_d_7bb67f_idx',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='start_date',
        ),
    ]
