# Generated by Django 5.2.7 on 2025-10-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visible_from", models.DateTimeField()),
                ("due_at", models.DateTimeField()),
                ("grade", models.CharField(blank=True, max_length=16)),
                (
                    "course_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.courseclass",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="catalog.subject"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("text", "Text"), ("image", "Image"), ("pdf", "PDF"), ("other", "Other")],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("s3_key", models.CharField(max_length=255)),
                ("bytes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="assignments.assignment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["course_class"], name="assignments_course__359a5f_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["visible_from"], name="assignments_visible_549811_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["due_at"], name="assignments_due_at_85c19f_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["assignment", "kind"], name="assignments_assignm_17c120_idx"),
        ),
    ]
