# Generated by Django 5.2.7 on 2025-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assignment",
            name="assignments_topic_i_3b1fb2_idx",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="topic",
        ),
        migrations.AddField(
            model_name="assignment",
            name="topics",
            field=models.ManyToManyField(blank=True, related_name="assignments", to="catalog.topic"),
        ),
    ]
