# Generated by Django 5.2.7 on 2025-10-23 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="subject_id",
            new_name="subject",
        ),
    ]
