# Generated by Django 5.2.7 on 2025-10-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_rename_subject_id_assignment_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="content",
            field=models.TextField(blank=True, help_text="텍스트 자료의 내용 (TEXT 타입일 때 사용)"),
        ),
    ]
