# Generated by Django 5.2.7 on 2025-10-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_remove_assignment_assignments_topic_i_3b1fb2_idx_and_more"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="course_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="courses.courseclass",
            ),
        ),
    ]
