# Generated by Django 5.2.7 on 2025-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_alter_assignment_course_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="bytes",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
