# Generated by Django 5.2.7 on 2025-10-24 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_material_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="content",
        ),
    ]
