# Generated by Django 5.2.7 on 2025-10-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0004_remove_material_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="summary",
            field=models.TextField(blank=True, help_text="summary text of the material"),
        ),
    ]
