# Generated by Django 5.2.7 on 2025-10-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_material_bytes'),
        ('courses', '0002_rename_title_courseclass_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.courseclass'),
        ),
    ]
