# Generated by Django 5.2.7 on 2025-11-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_material_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_question_created',
            field=models.BooleanField(default=False),
        ),
    ]
