# Generated by Django 5.2.7 on 2025-11-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_is_question_created'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignment',
            name='assignments_visible_549811_idx',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='visible_from',
        ),
    ]
