# Generated by Django 5.2.7 on 2025-10-23 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0006_assignment_grade_alter_assignment_course_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="topics",
        ),
    ]
