# Generated by Django 5.2.7 on 2025-10-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField(help_text="문항 번호 (1..N)")),
                ("content", models.CharField(blank=True, max_length=255)),
                ("topic", models.CharField(blank=True, help_text="단원", max_length=64, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("model_answer", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_question",
                    models.ForeignKey(
                        blank=True,
                        help_text="The base question this one is derived from (null if this is a base question)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tail_questions",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["personal_assignment_id", "number"],
            },
        ),
    ]
