# Generated by Django 5.2.7 on 2025-10-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField(help_text="문항 번호 (1..N)")),
                ("content", models.CharField(blank=True, max_length=255)),
                ("hint", models.CharField(blank=True, max_length=255, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("model_answer", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "personal_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="submissions.personalassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["personal_assignment_id", "number"],
                "indexes": [
                    models.Index(fields=["personal_assignment", "number"], name="questions_q_persona_a03610_idx")
                ],
                "unique_together": {("personal_assignment", "number")},
            },
        ),
    ]
