# Generated by Django 5.2.7 on 2025-10-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="personal_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="submissions.personalassignment",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["personal_assignment", "number"], name="questions_q_persona_a03610_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("personal_assignment", "number")},
        ),
    ]
