# Generated by Django 5.2.7 on 2025-10-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="base_question",
            field=models.ForeignKey(
                blank=True,
                help_text="The base question this one is derived from (null if this is a base question)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tail_questions",
                to="questions.question",
            ),
        ),
    ]
