# Generated by Django 5.2.7 on 2025-10-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_question_base_question"),
        ("submissions", "0002_alter_answer_question_delete_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")], default="medium", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="personal_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="submissions.personalassignment",
            ),
        ),
    ]
