# Generated by Django 5.2.7 on 2025-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="recalled_num",
            field=models.IntegerField(default=0, help_text="몇 번째 (tail) question인지 나타내는 숫자"),
        ),
    ]
