# Generated by Django 5.2.7 on 2025-10-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_question_difficulty_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="hint",
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.CharField(blank=True, help_text="단원", max_length=64, null=True),
        ),
    ]
