# Generated by Django 5.2.7 on 2025-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_question_recalled_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="recalled_num",
            field=models.IntegerField(help_text="몇 번째 (tail) question인지 나타내는 숫자"),
        ),
    ]
