# Generated by Django 5.2.7 on 2025-10-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0004_alter_question_recalled_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="achievement_code",
            field=models.CharField(blank=True, help_text="교육과정 성취기준", max_length=32, null=True),
        ),
    ]
