# Generated by Django 5.2.7 on 2025-10-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_question_achievement_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="personal_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="submissions.personalassignment",
            ),
        ),
    ]
