# Generated by Django 5.2.7 on 2025-10-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_achievement_code'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='question',
            name='personal_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='submissions.personalassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('personal_assignment', 'number', 'recalled_num')},
        ),
    ]
