# Generated by Django 5.2.7 on 2025-10-26 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_unique_together_and_more'),
        ('questions', '0007_alter_question_personal_assignment'),
    ]

    operations = [
    ]
