# Generated by Django 5.2.7 on 2025-11-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherFeedback',
        ),
    ]
